### ISSUE TITLE
在 Mac 下编译失败

### ISSUE THREAD

**Issue by b1gm0use** [Chaphlagical/GAMES106-HW5#9]
报错如下：

```
[cmake] -- Checking for module 'minizip'
[cmake] --   No package 'minizip' found
[cmake] INFO Hunter enabled or RT-extension not found. glTF import/export will be built without Open3DGC-compression.
[cmake] -- Enabled importer formats: AMF 3DS AC ASE ASSBIN B3D BVH COLLADA DXF CSM HMP IRRMESH IQM IRR LWO LWS M3D MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
[cmake] -- Disabled importer formats:
[cmake] -- Enabled exporter formats: OBJ OPENGEX PLY 3DS ASSBIN ASSXML M3D COLLADA FBX STL X X3D GLTF 3MF PBRT ASSJSON STEP
[cmake] -- Disabled exporter formats:
[cmake] -- Treating all warnings as errors (for assimp library only)
[cmake] CMake Error at cmake/assimp.cmake:22 (set_target_properties):
[cmake]   set_target_properties Can not find target to add properties to:
[cmake]   UpdateAssimpLibsDebugSymbolsAndDLLs
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:12 (include)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[proc] The command: /usr/local/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ -S/Users/b1gm0use/GitProjects/GAMES106-HW5 -B/Users/b1gm0use/GitProjects/GAMES106-HW5/build -G "Unix Makefiles" exited with code: 1
```

**Comment by libreliu** [comment]
感谢反馈！
方便的话，您可以看下 #10 是否可以解决您的问题？

**Comment by b1gm0use** [comment]
还是有问题

[build] /Users/b1gm0use/GitProjects/GAMES106-HW5/build/_deps/assimp-src/code/PostProcessing/ValidateDataStructure.cpp:83:22: error: 'vsprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use vsnprintf(3) instead. [-Werror,-Wdeprecated-declarations]
[build]     const int iLen = vsprintf(szBuffer, msg, args);
[build]                      ^
[build] /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdio.h:207:1: note: 'vsprintf' has been explicitly marked deprecated here
[build] __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use vsnprintf(3) instead.")
[build] ^
[build] /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
[build]         #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
[build]                                                       ^
[build] /Users/b1gm0use/GitProjects/GAMES106-HW5/build/_deps/assimp-src/code/PostProcessing/ValidateDataStructure.cpp:98:22: error: 'vsprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use vsnprintf(3) instead. [-Werror,-Wdeprecated-declarations]
[build]     const int iLen = vsprintf(szBuffer, msg, args);
[build]                      ^
[build] /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdio.h:207:1: note: 'vsprintf' has been explicitly marked deprecated here
[build] __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use vsnprintf(3) instead.")


不过上面的错误可以在 CMakeList.txt 里添加 add_compile_options(-Wno-deprecated-declarations) 解决，然后继续编译出现链接错误：

[build] [100%] Linking CXX executable GAMES106-HW5
[build] Undefined symbols for architecture x86_64:
[build]   "std::__1::pmr::memory_resource::~memory_resource()", referenced from:
[build]       std::__1::pmr::synchronized_pool_resource::synchronized_pool_resource[abi:v160006](std::__1::pmr::pool_options const&, std::__1::pmr::memory_resource*) in mesh_reduction.cpp.o
[build]       std::__1::pmr::synchronized_pool_resource::~synchronized_pool_resource() in mesh_reduction.cpp.o
[build]       std::__1::pmr::unsynchronized_pool_resource::~unsynchronized_pool_resource() in mesh_reduction.cpp.o
[build]   "std::__1::pmr::get_default_resource()", referenced from:
[build]       std::__1::pmr::synchronized_pool_resource::synchronized_pool_resource[abi:v160006]() in mesh_reduction.cpp.o
[build]   "std::__1::pmr::unsynchronized_pool_resource::release()", referenced from:
[build]       std::__1::pmr::unsynchronized_pool_resource::~unsynchronized_pool_resource() in mesh_reduction.cpp.o
[build]   "std::__1::pmr::unsynchronized_pool_resource::unsynchronized_pool_resource(std::__1::pmr::pool_options const&, std::__1::pmr::memory_resource*)", referenced from:
[build]       std::__1::pmr::synchronized_pool_resource::synchronized_pool_resource[abi:v160006](std::__1::pmr::pool_options const&, std::__1::pmr::memory_resource*) in mesh_reduction.cpp.o
[build]   "vtable for std::__1::pmr::memory_resource", referenced from:
[build]       std::__1::pmr::memory_resource::memory_resource() in mesh_reduction.cpp.o
[build]   NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
[build]   "vtable for std::__1::pmr::synchronized_pool_resource", referenced from:
[build]       std::__1::pmr::synchronized_pool_resource::synchronized_pool_resource[abi:v160006](std::__1::pmr::pool_options const&, std::__1::pmr::memory_resource*) in mesh_reduction.cpp.o
[build]       std::__1::pmr::synchronized_pool_resource::~synchronized_pool_resource() in mesh_reduction.cpp.o
[build]   NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
[build]   "vtable for std::__1::pmr::unsynchronized_pool_resource", referenced from:
[build]       std::__1::pmr::unsynchronized_pool_resource::~unsynchronized_pool_resource() in mesh_reduction.cpp.o
[build]   NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
[build] ld: symbol(s) not found for architecture x86_64
[build] clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
[build] make[2]: *** [GAMES106-HW5] Error 1
[build] make[1]: *** [CMakeFiles/GAMES106-HW5.dir/all] Error 2
[build] make: *** [all] Error 2

**Comment by b1gm0use** [comment]
补充一下，用 clang 14 会在编译时失败，提示没有 <memory_reource> 头文件，用 clang 16 会报上面的错误。用 gcc 13 报错就更奇怪了。

**Comment by b1gm0use** [comment]
补充一下系统信息： macOS 13.4.1， Xcode Version 14.3.1 (14E300c)，Apple M1

**Comment by libreliu** [comment]
这个问题似乎是使用的 C++ standard library 不支持 std::pmr::memory_resource （其应该涵盖在支持 C++17 的标准库中）？
我在 Linux 下面的 clang14 并不能 repro 这个问题。gcc 13 和 clang 15 会有一些别的问题 （比如 libigl 有个地方缺 `<cstdint>` 的引用），但是似乎都与上面的问题没有关系。

由于手边没有 Apple M1 的设备，这个 bug 可能我们没有资源来修复... 我怀疑这个问题可能与您的编译工具链有关系。

您也可以考虑用 OpenMesh 并注释所有为引入 UHEMesh 而进行的对 memory_resource 的引入，来 walkaround 此问题。

我和 @Chaphlagical 在 Windows (+msvc2019, 2022) 和 Linux (ArchLinux, gcc12) 下可以编译并运行...

**Comment by b1gm0use** [comment]
搞定了，是我这边 toolchain 的问题。大概就是 xcode 自带的 clang 14 貌似实现不完全，memory_resource 还在 experimental 下，没有实现 synchronized_pool_resource（我暂时是这么理解的，还不是特别明白）。改用 homebrew 安装的 clang 16 就需要配置环境，比较重要的是 LDFLAGS 的部分，使用 `brew info llvm` 就能看到，修改完毕以后就可以修正上面的问题了。 

另外还需要修改的是在 CMakeList.txt 中添加 
`add_compile_options(-Wno-deprecated-declarations)`
和
`target_link_options(${PROJECT_NAME} PRIVATE "-L/usr/local/opt/llvm/lib/c++" "-Wl,-rpath,/usr/local/opt/llvm/lib/c++")`

多谢 @libreliu 帮忙处理问题，现在问题已经解决。我把这个 Issue 关闭了。
